Rl datasets
JuliaReinforcementLearning/ReinforcementLearning.jl pull request #384
Opened 2021-07-18 17:08 UTC by Mobius1D

PR Checklist

- [ ] Update NEWS.md?

Implemented functionality for getting NamedTuple for d4rl, d4rl_atari, d4rl_pybullet with a sample function.

2021-07-18 17:11 UTC, Mobius1D commented
The spacing is kinda bad for the files. Will change it ASAP

2021-07-19 03:13 UTC, findmyway requested changes

2021-07-19 03:13 UTC, findmyway commented on src/ReinforcementLearningDatasets/.github/workflows/CompatHelper.yml
> +name: CompatHelper
The folder ` src/ReinforcementLearningDatasets/.github` can be safely removed.

2021-07-19 03:13 UTC, findmyway commented on src/ReinforcementLearningDatasets/.github/workflows/TagBot.yml
> +name: TagBot
save as above

2021-07-19 03:13 UTC, findmyway commented on src/ReinforcementLearningDatasets/.gitignore
> +
same as above

2021-07-19 03:13 UTC, findmyway commented on src/ReinforcementLearningDatasets/Project.toml
> +julia = "1"
Add compat section of the `deps`

2021-07-19 03:13 UTC, findmyway commented on src/ReinforcementLearningDatasets/README.md
> +# ReinforcementLearningDatasets
Maybe add some descriptions here?

2021-07-19 03:13 UTC, findmyway commented on src/ReinforcementLearningDatasets/src/3rd_party/3rd_party_datasets.jl
> +function get_dataset(env_name::String, package::String)
Could you explain the `env_name` and `package` in the doc string?

2021-07-19 03:13 UTC, findmyway commented on src/ReinforcementLearningDatasets/src/3rd_party/3rd_party_datasets.jl
> +    if package == "d4rl"
Maybe set the `package` to `"d4rl"` by default?

2021-07-19 16:15 UTC, findmyway commented
Fix the spell check first?

2021-07-20 02:19 UTC, findmyway requested changes
I understand this is a draft version, but we still need to make it workable. First, the project.toml is not updated. Many dependencies are not included, though most of them should be removed later. Second, a simple test is not included yet. You should add the tests in CI.yml file under .github. The current CI failure is another thing. I'll fix it soon.

2021-07-28 04:46 UTC, Mobius1D commented
I think we can close this out.

2021-07-28 04:46 UTC, closed without merging