Mvnormlogpdf
JuliaReinforcementLearning/ReinforcementLearning.jl pull request #848
Opened 2023-03-15 10:51 UTC by HenriDeh

PR Checklist

- [ ] Update NEWS.md?
- [ ] Unit tests for all structs / functions?
- [ ] Integration and correctness tests using a simple env?
- [ ] PR Review?
- [ ] Add or update documentation?
- [ ] Write docstrings for new methods?

2023-03-15 10:52 UTC, HenriDeh commented
@jeremiahpslewis What are the tests you felt were missing for mvnormlogpdf ?

2023-03-15 12:04 UTC, jeremiahpslewis commented on src/ReinforcementLearningZoo/src/algorithms/policy_gradient/ppo.jl
> +import ReinforcementLearningCore.normlogpdf
Should we make this consistent with the previous example and do:
```suggestion
import ReinforcementLearningCore: normlogpdf
```

2023-03-15 12:04 UTC, jeremiahpslewis commented on src/ReinforcementLearningZoo/src/algorithms/policy_gradient/vmpo.jl
> +import ReinforcementLearningCore.normlogpdf
Should we make this consistent with the first example and do:
```suggestion
import ReinforcementLearningCore: normlogpdf
```

2023-03-15 12:05 UTC, jeremiahpslewis requested changes
Just have a few ideas for minor tweaks, let me know what you think!

2023-03-15 12:43 UTC, HenriDeh commented on src/ReinforcementLearningCore/src/utils/distributions.jl
> +    logp = reduce(hcat, [l(k) for k in axes(x, 3)])
Yes, this is really tricky to optimize, I've tried quite a lot to minimize allocations. The thing is, this must be differentiable (no array mutation as long as we work with Zygote), and GPU compatible (no array indexing). I was told that reduce hcat on an array comprehension is well optimized by the compiler. 

Now that I write this, I see that there is array indexing here. I'll run some tests locally.

2023-03-15 16:12 UTC, jeremiahpslewis commented
Just going through the different functions, a question came up...this version is faster on a CPU, would it work on a GPU?
```julia
function logdetLorU(LorU::CuArray)
    return 2*log(prod(diag(LorU)))
end
```

2023-03-15 16:24 UTC, jeremiahpslewis commented
And what about pulling out the `2` from `logdetLorU` and using `const log4π` instead? Seems to speed things up by nearly 10%.

2023-03-15 16:34 UTC, jeremiahpslewis commented on src/ReinforcementLearningCore/src/utils/distributions.jl
> +    logp = reduce(hcat, [l(k) for k in axes(x, 3)])
Want to use a tuple here instead of a vect?

```suggestion
    logp = reduce(hcat, (l(k) for k in axes(x, 3)))
```

2023-03-16 11:52 UTC, HenriDeh commented
> And what about pulling out the `2` from `logdetLorU` and using `const log4π` instead? Seems to speed things up by ~5%.

Do you mean replacing the function by "half_logdetLorU" and multiplying its output by two when called ?

2023-03-16 11:57 UTC, HenriDeh commented
> And what about pulling out the `2` from `logdetLorU` and using `const log4π` instead? Seems to speed things up by ~5%.

Do you mean in replacing the log2pi in mvnormlogpdf? Because `a*log(2pi) + logdet != a*log(4pi) + logdet/2` so I'm not sure what you are suggesting.

2023-03-16 12:15 UTC, jeremiahpslewis commented
> > And what about pulling out the `2` from `logdetLorU` and using `const log4π` instead? Seems to speed things up by ~5%.
> 
> Do you mean in replacing the log2pi in mvnormlogpdf? Because `a*log(2pi) + logdet != a*log(4pi) + logdet/2` so I'm not sure what you are suggesting.

Yup, let's ignore that idea. 😆

2023-03-16 14:06 UTC, HenriDeh commented
> Just going through the different functions, a question came up...this version is faster on a CPU, would it work on a GPU?
> 
> ```julia
> function logdetLorU(LorU::CuArray)
>     return 2*log(prod(diag(LorU)))
> end
> ```

It does not. 
![image](https://user-images.githubusercontent.com/47037088/225642392-77ada830-1acb-419c-9540-ec7f3afa5e47.png)
Anyways, the CPU fallback below is much faster as it uses the built-in logdet function of LinearAlgebra.

2023-03-23 14:13 UTC, closed without merging