reintroduce args kwargs
JuliaReinforcementLearning/ReinforcementLearning.jl pull request #893
Opened 2023-05-31 12:31 UTC by HenriDeh

Propagation of args and kwargs from the agent to the policy during `plan!` disappeared during the refactor. This reintroduces that.

2023-05-31 13:09 UTC, HenriDeh commented
I see based on the failed test that it was on purpose. Args and kwargs propagation are usefull to control the behavior of policies for example if one wants to not sample in a "testmode".

2023-05-31 15:25 UTC, jeremiahpslewis commented
I get type instability errors in my project [AlgorithmicCompetition.jl](https://github.com/jeremiahpslewis/AlgorithmicCompetition.jl) when this change is made. I think it's because we then lose the ability to use multiple dispatch (?) as efficiently.

```julia
julia> @report_opt RLBase.plan!(experiment.policy, experiment.env)
═════ 3 possible errors found ═════
┌ @ /Users/jpslewis/git/AlgorithmicCompetition.jl/src/AIAPC2020/run.jl:9 plan!(multiagent[AlgorithmicCompetition.Symbol([quote])], env, AlgorithmicCompetition.Symbol([quote]))
│┌ @ /Users/jpslewis/.julia/packages/ReinforcementLearningCore/JuUrI/src/policies/agent/base.jl:72 action = plan!(agent.policy, env, p)
││┌ @ /Users/jpslewis/.julia/packages/ReinforcementLearningCore/JuUrI/src/policies/q_based_policy.jl:29 plan!(p.explorer, p.learner, env, player)
│││┌ @ /Users/jpslewis/.julia/packages/ReinforcementLearningCore/JuUrI/src/policies/q_based_policy.jl:33 legal_action_space_ = legal_action_space_mask(env, player)
││││┌ @ /Users/jpslewis/git/AlgorithmicCompetition.jl/src/AIAPC2020/env.jl:128 getindex(tuple(AlgorithmicCompetition.SA), 1 AlgorithmicCompetition.:(:) 15...)
│││││┌ @ /Users/jpslewis/.julia/packages/StaticArrays/J9itA/src/initializers.jl:31 similar_type(sa, Size(StaticArrays.length(xs)))(xs)
││││││┌ @ /Users/jpslewis/.julia/packages/StaticArrays/J9itA/src/convert.jl:162 SA′ = StaticArrays.construct_type(SA, x)
│││││││┌ @ /Users/jpslewis/.julia/packages/StaticArrays/J9itA/src/convert.jl:87 StaticArrays.adapt_size(SA, x)
││││││││┌ @ /Users/jpslewis/.julia/packages/StaticArrays/J9itA/src/convert.jl:115 StaticArrays.tuple_length(SZ)
│││││││││┌ @ /Users/jpslewis/.julia/packages/StaticArraysCore/U2Z1K/src/StaticArraysCore.jl:47 StaticArraysCore.length(%1)
││││││││││ runtime dispatch detected: StaticArraysCore.length(%1::Any)::Any
│││││││││└─────────────────────────────────────────────────────────────────────────────────────
││││││┌ @ /Users/jpslewis/.julia/packages/StaticArrays/J9itA/src/convert.jl:163 SA′(x)
│││││││┌ @ /Users/jpslewis/.julia/packages/StaticArraysCore/U2Z1K/src/StaticArraysCore.jl:117 StaticArraysCore.tuple_prod(S)
││││││││┌ @ /Users/jpslewis/.julia/packages/StaticArraysCore/U2Z1K/src/StaticArraysCore.jl:49 StaticArraysCore.length(%1)
│││││││││ runtime dispatch detected: StaticArraysCore.length(%1::Any)::Any
││││││││└─────────────────────────────────────────────────────────────────────────────────────
││││││││┌ @ /Users/jpslewis/.julia/packages/StaticArraysCore/U2Z1K/src/StaticArraysCore.jl:49 %2 StaticArraysCore.:(==) 0
│││││││││ runtime dispatch detected: (%2::Any StaticArraysCore.:(==) 0)::Any
││││││││└─────────────────────────────────────────────────────────────────────────────────────
```

I dropped the args and kwargs as they aren't integrated into the `run` functions and it seemed more effective to make policies 'environment aware', e.g. you could have a test mode flag attached to an env which the policy respects. Thoughts?

2023-05-31 15:27 UTC, jeremiahpslewis commented
More concisely: it's not clear to me what can't be achieved with args/kwargs more directly by modifying / extending a policy or env.

2023-05-31 16:04 UTC, jeremiahpslewis requested changes
Posted my take above, let me know what you think. 😅

2023-05-31 16:25 UTC, zsunberg commented
Passing `args` and `kwargs` through indiscriminately has a bad smell to me. There is no documented contract between different developers about what those args should be. I agree with @jeremiahpslewis 's take. However, it's not clear to me why there should be any performance penalty.

If someone wants to add extra functionality that isn't specified in the `plan!` interface, they should add their own additional functions to interact with the policy/agent rather than passing additional arguments to `plan!` (note: I am not that familiar with this interface, so I might be missing something)

2023-06-01 07:14 UTC, HenriDeh commented
I find it surprising that there would be any multiple dispatch issue with this. The use of args and kwargs is common in julia. 
I guess it is true that `Agent` is meant to be used for training in the run loop. I'm ok with closing this and using the policy directly instead of the agent in deployment.

2023-06-01 07:14 UTC, closed without merging