Refactor TRPO and VPG with EpisodesSampler
JuliaReinforcementLearning/ReinforcementLearning.jl pull request #952
Opened 2023-08-09 14:38 UTC by HenriDeh

PR Checklist

- [ ] Update NEWS.md?
- [ ] Unit tests for all structs / functions?
- [ ] Integration and correctness tests using a simple env?
- [ ] PR Review?
- [ ] Add or update documentation?
- [ ] Write docstrings for new methods?

2023-08-09 14:44 UTC, HenriDeh commented
CI can't pass without 3.3 released

2023-08-10 09:03 UTC, HenriDeh commented
I can't get buildkite to rerun now that Traj 0.3.3 is released. But tests pass. Note that this PR does not make any promise on the correctness  of the two algorithms.

2023-08-10 09:49 UTC, HenriDeh commented
Found some issues. Do not review yet.

2023-08-10 10:35 UTC, HenriDeh commented
I concluded that the algorithms are broken but due to additional reasons that are not tied to the refactor. Hence, I kept the algorithms commented but at least the optimise! functions are refactored and may serve as an example for other refactors in the future. It's all I can do in this PR. Further fixing of policy gradient algorithm require contributors knowledgeable about how they work.

2023-08-10 12:35 UTC, jeremiahpslewis submitted a review, later dismissed

2023-08-11 09:09 UTC, HenriDeh commented
need a new approval due to conflicts

2023-08-11 10:17 UTC, jeremiahpslewis approved these changes

2023-08-11 10:17 UTC, jeremiahpslewis commented on src/ReinforcementLearningCore/Project.toml
> +ReinforcementLearningTrajectories = "0.3.3"
```suggestion
ReinforcementLearningTrajectories = "^0.3.3"
```
I think we want [0.3.3,0.4), right?

2023-08-11 10:17 UTC, jeremiahpslewis commented on src/ReinforcementLearningExperiments/Project.toml
> +ReinforcementLearningZoo = "0.8.3"
```suggestion
ReinforcementLearningZoo = "^0.8.3"
```
Same as above

2023-08-11 10:17 UTC, jeremiahpslewis commented on src/ReinforcementLearningZoo/Project.toml
> +ReinforcementLearningCore = "0.12.3, 0.13"
```suggestion
ReinforcementLearningCore = "^0.12.3, 0.13"
```

2023-08-11 10:17 UTC, jeremiahpslewis requested changes
see above

2023-08-11 13:03 UTC, jeremiahpslewis approved these changes

2023-08-11 13:15 UTC, merged